<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('products')->delete();

        \DB::table('products')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'name' => '{"fr": "HEIDELBERG", "ar": "هايدلبرغ", "en": "HEIDELBERG"}',
                    'description' => '{"fr":"La Heidelberg GTOV signifie GTO (Grande Format Tiegel Offset) + V (Vierfarben), ce qui indique qu\'il s\'agit d\'une presse offset à alimentation feuille avec quatre couleurs. Elle est couramment utilisée pour les travaux d\'impression commerciaux tels que les brochures, l\'emballage, les cartes de visite et les catalogues. La machine prend en charge le format A3, jusqu\'à environ 36 x 52 cm. Le « V » dans GTOV signifie « Vierfarben » en allemand, ce qui veut dire « quatre couleurs ». La machine est équipée de 4 unités d\'impression pour le Cyan, Magenta, Jaune et Noir (CMJN), permettant l\'impression en couleur complète en un seul passage.","en":"The Heidelberg GTOV stands for GTO (Großformat-Tiegel Offset) + V (Vierfarben), meaning it is a 4-color sheet-fed offset printing machine. It is commonly used for commercial printing jobs such as brochures, packaging, business cards, and catalogs. The machine supports A3 format paper sizes, up to approximately 36 x 52 cm. The \\"V\\" in GTOV means \\"Vierfarben\\" in German, which translates to \\"four colors.\\" The machine is equipped with 4 printing units for Cyan, Magenta, Yellow, and Black (CMYK), allowing full-color printing in a single pass","ar":"تعني Heidelberg GTOV: GTO (آلة الطباعة الأوفست الكبيرة) + V (الألوان الأربعة)، مما يعني أنها آلة طباعة أوفست تغذية بالورق مزودة بأربعة ألوان. تُستخدم عادةً في أعمال الطباعة التجارية مثل الكتيبات، التعبئة والتغليف، بطاقات الأعمال، والكتالوجات. تدعم الآلة حجم ورق A3 يصل إلى حوالي 36 × 52 سم.الحرف \\"V\\" في GTOV يعني \\"Vierfarben\\" بالألمانية، والذي يعني \\"الألوان الأربعة\\". تحتوي الآلة على 4 وحدات طباعة لكل من السماوي (السيان)، الأرجواني (المجنطة)، الأصفر، والأسود (CMYK)، مما يسمح بالطباعة بالألوان الكاملة في مرور واحد."}',
                    'slug' => 'heidelberg',
                    'model' => '{"fr":"GTOV"}',
                    'brand' => '{"ar": "هايدلبرغ", "en": "HEIDELBERG", "fr": "HEIDELBERG"}',
                    'type' => '{"ar": "سلسلة 690015", "en": "serie 690015", "fr": "serie 690015"}',
                    'speed' => '{"ar": "ما يصل إلى 8000 ورقة في الساعة", "en": "Up to 8,000 sheets per hour", "fr": "Jusqu`à 8 000 feuilles par heure"}',
                    'resolution' => NULL,
                    'max_print_size' => '{"ar": "34 × 50 سم (حوالي 13.39 × 19.69 بوصة)", "en": "34 x 50 cm (approximately 13.39 x 19.69 inches)", "fr": "34 x 50 cm (environ 13,39 x 19,69 pouces)"}',
                    'color_capability' => 1,
                    'duplex' => 1,
                    'connectivity' => '{"ar": "لا يوجد اتصال رقمي أو شبكي", "en": "No digital or network connectivity", "fr": "Aucune connectivité numérique ou réseau"}',
                    'power_consumption' => '{"ar": "من 4 إلى 6 كيلو وات أثناء التشغيل", "en": "4 to 6 kW during operation", "fr": "4 à 6 kW en fonctionnement"}',
                    'condition' => '{"ar": "مستخدم", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 8500.0,
                    'warranty' => NULL,
                    'manufacture_year' => '1987',
                    'images' => '["products\\/01JVHFFSPJNCVQ09DJQ5ZCW2EA.webp","products\\/01JVHFFSPX6HM03X5SCNPWWHES.webp"]',
                    'category_id' => 1,
                    'created_at' => '2025-01-11 13:29:02',
                    'updated_at' => '2025-05-18 10:36:59',
                ),
            1 =>
                array(
                    'id' => 2,
                    'name' => '{"fr": "RYOBI", "ar": "ريوبي", "en": "RYOBI"}',
                    'description' => '{"fr":"La RYOBI 524 GX est une presse offset feuille à feuille à 4 couleurs avec une unité de vernis. Elle est largement utilisée pour les impressions commerciales de haute qualité telles que les brochures, les catalogues, les cartes de visite et les emballages. Ce modèle de 2007 offre une précision d’impression exceptionnelle, un changement de plaques rapide grâce au système semi-automatique, ainsi qu’un pupitre de commande centralisé pour une gestion simplifiée. L’unité de vernis permet une finition brillante ou mate pour améliorer l’apparence des imprimés.","en":"The RYOBI 524 GX is a 4-color sheet-fed offset printing press with a coating unit. Widely used for high-quality commercial printing like brochures, catalogs, business cards, and packaging. This 2007 model offers exceptional print precision, quick plate changes with a semi-automatic system, and a centralized control panel for easy operation. The coating unit allows for glossy or matte finishes to enhance the final product.","ar":"ريوبي 524 GX هي آلة طباعة أوفست تغذية بالورق مزودة بأربعة ألوان ووحدة تلميع (ورنيش). تُستخدم على نطاق واسع في الطباعة التجارية عالية الجودة مثل الكتيبات والكتالوجات وبطاقات العمل والتغليف. يتميز هذا الطراز لعام 2007 بدقة طباعة استثنائية، وتغيير سريع للألواح عبر نظام شبه أوتوماتيكي، ولوحة تحكم مركزية لتسهيل التشغيل. تسمح وحدة التلميع بالحصول على تشطيبات لامعة أو غير لامعة لتعزيز جودة المنتج النهائي."}',
                    'slug' => 'ryobi-524-gx',
                    'model' => '{"fr": "524 GX", "ar": "524 GX", "en": "524 GX"}',
                    'brand' => '{"ar": "ريوبي", "en": "RYOBI", "fr": "RYOBI"}',
                    'type' => '{"ar": "أوفست بأربعة ألوان مع وحدة ورنيش", "en": "4-color offset with coating unit", "fr": "Offset 4 couleurs avec vernis"}',
                    'speed' => '{"ar": "حتى 13,000 ورقة في الساعة", "en": "Up to 13,000 sheets per hour", "fr": "Jusqu’à 13 000 feuilles par heure"}',
                    'resolution' => '{"en":null}',
                    'max_print_size' => '{"ar": "52 × 36 سم", "en": "52 x 36 cm", "fr": "52 x 36 cm"}',
                    'color_capability' => 1,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "لا توجد إمكانية اتصال رقمي", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "تقريبًا 7 كيلو وات أثناء التشغيل", "en": "Approx. 7 kW during operation", "fr": "Env. 7 kW en fonctionnement"}',
                    'condition' => '{"ar": "مستخدم", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 14500.0,
                    'warranty' => NULL,
                    'manufacture_year' => '2007',
                    'images' => '["products\\/01JX3JW88YJW1RQ05HX0YAEXS4.jpg","products\\/01JX3JW8A8HY7DYEBQK2W9590T.jpg"]',
                    'category_id' => 1,
                    'created_at' => '2025-06-07 12:00:00',
                    'updated_at' => '2025-06-06 21:38:15',
                ),
            2 =>
                array(
                    'id' => 3,
                    'name' => '{"fr": "HEIDELBERG", "ar": "هايدلبرغ", "en": "HEIDELBERG"}',
                    'description' => '{"fr":"La presse HEIDELBERG MOZ de 1991 fait partie de la série 612129, connue pour sa robustesse et sa fiabilité. Cette presse offset feuille à feuille est conçue pour les travaux d\'impression de moyenne à grande série avec une excellente qualité. Elle dispose d\'un système de contrôle avancé pour assurer une impression précise et constante, ainsi que d\'un changement rapide des plaques. La machine est adaptée à une grande variété de supports papier, offrant polyvalence et productivité élevée.","en":"The 1991 HEIDELBERG MOZ press belongs to series 612129, renowned for its durability and reliability. This sheet-fed offset press is designed for medium to large print runs with excellent quality. It features an advanced control system to ensure precise and consistent printing, as well as quick plate changes. The machine is suitable for a wide variety of paper stocks, providing versatility and high productivity.","ar":"تنتمي ماكينة هايدلبرغ MOZ لعام 1991 إلى السلسلة 612129، المعروفة بمتانتها وموثوقيتها. هذه الماكينة هي آلة طباعة أوفست تغذية بالورق مصممة للأعمال الطباعية متوسطة إلى كبيرة الحجم بجودة ممتازة. تتميز بنظام تحكم متقدم لضمان طباعة دقيقة ومتسقة، بالإضافة إلى تغيير سريع للألواح. تناسب الماكينة مجموعة واسعة من أنواع الورق، مما يوفر تعددية إنتاجية عالية."}',
                    'slug' => 'heidelberg-moz-612129',
                    'model' => '{"fr": "MOZ", "ar": "MOZ", "en": "MOZ"}',
                    'brand' => '{"ar": "هايدلبرغ", "en": "HEIDELBERG", "fr": "HEIDELBERG"}',
                    'type' => '{"ar": "أوفست تغذية ورق", "en": "Sheet-fed offset", "fr": "Offset feuille"}',
                    'speed' => '{"ar": "حتى 10,000 ورقة في الساعة", "en": "Up to 10,000 sheets per hour", "fr": "Jusqu’à 10 000 feuilles par heure"}',
                    'resolution' => '{"en":null}',
                    'max_print_size' => '{"ar": "40 × 60 سم", "en": "40 x 60 cm", "fr": "40 x 60 cm"}',
                    'color_capability' => 1,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "بدون اتصال رقمي", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "حوالي 6 كيلو وات أثناء التشغيل", "en": "Approx. 6 kW during operation", "fr": "Env. 6 kW en fonctionnement"}',
                    'condition' => '{"ar": "مستخدم", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 12000.0,
                    'warranty' => NULL,
                    'manufacture_year' => '1991',
                    'images' => '["products\\/01JX3KBP9RYXV3X9QQZNAZ0P43.png","products\\/01JX3KBPA57WH8K10HBD57RV3Z.png"]',
                    'category_id' => 4,
                    'created_at' => '2025-06-07 12:10:00',
                    'updated_at' => '2025-06-06 21:46:40',
                ),
            3 =>
                array(
                    'id' => 4,
                    'name' => '{"fr": "HEIDELBERG", "ar": "هايدلبرغ", "en": "HEIDELBERG"}',
                    'description' => '{"fr":"La HEIDELBERG QM46, fabriquée en 1999, est une presse d\'impression offset compacte à 2 couleurs connue sous le nom de Quickmaster. Elle est idéale pour les petits et moyens tirages avec une excellente qualité d\'impression. Cette machine offre un changement rapide des plaques et un contrôle précis de la pression pour assurer des résultats nets. Sa conception compacte la rend adaptée aux ateliers disposant d\'un espace limité, tout en conservant une productivité élevée.","en":"The 1999 HEIDELBERG QM46 is a compact 2-color offset printing press known as Quickmaster. It is ideal for small to medium print runs with excellent print quality. This machine offers quick plate changes and precise pressure control to ensure sharp results. Its compact design makes it suitable for workshops with limited space while maintaining high productivity.","ar":"هايدلبرغ QM46، المصنعة عام 1999، هي آلة طباعة أوفست مدمجة ذات لونين تعرف باسم Quickmaster. مثالية للطباعة بكميات صغيرة إلى متوسطة مع جودة طباعة ممتازة. توفر هذه الماكينة تغييرًا سريعًا للألواح وتحكمًا دقيقًا في الضغط لضمان نتائج واضحة. تصميمها المدمج يجعلها مناسبة للورش ذات المساحات المحدودة مع الحفاظ على إنتاجية عالية."}',
                    'slug' => 'heidelberg-qm46-quickmaster',
                    'model' => '{"fr": "QM46", "ar": "QM46", "en": "QM46"}',
                    'brand' => '{"ar": "هايدلبرغ", "en": "HEIDELBERG", "fr": "HEIDELBERG"}',
                    'type' => '{"ar": "أوفست لونين", "en": "2-color offset", "fr": "Offset 2 couleurs"}',
                    'speed' => '{"ar": "حتى 7,000 ورقة في الساعة", "en": "Up to 7,000 sheets per hour", "fr": "Jusqu’à 7 000 feuilles par heure"}',
                    'resolution' => '{"en":null}',
                    'max_print_size' => '{"ar": "46 × 32 سم", "en": "46 x 32 cm", "fr": "46 x 32 cm"}',
                    'color_capability' => 1,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "بدون اتصال رقمي", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "حوالي 4.5 كيلو وات أثناء التشغيل", "en": "Approx. 4.5 kW during operation", "fr": "Env. 4,5 kW en fonctionnement"}',
                    'condition' => '{"ar": "مستخدم", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 9500.0,
                    'warranty' => NULL,
                    'manufacture_year' => '1999',
                    'images' => '["products\\/01JX3KPR3TJ21WPPZT6CGC8RM4.jpg","products\\/01JX3KPR4G87DW54N33HZW79ZP.jpg","products\\/01JX3KPR4R0AB7A6H7QDKBXAPE.jpg"]',
                    'category_id' => 4,
                    'created_at' => '2025-06-07 12:20:00',
                    'updated_at' => '2025-06-06 21:52:43',
                ),
            4 =>
                array(
                    'id' => 5,
                    'name' => '{"fr": "HEIDELBERG", "ar": "هايدلبرغ", "en": "HEIDELBERG"}',
                    'description' => '{"fr":"La presse HEIDELBERG GTOZ de 1995, équipée NP, est une machine offset feuille polyvalente et fiable. Elle est idéale pour des tirages courts à moyens avec une qualité d\'impression élevée. Équipée du système NP, elle offre une meilleure précision dans l\'encrage et un contrôle optimisé des couleurs. Cette presse est appréciée pour sa robustesse et sa facilité d\'utilisation, adaptée aux petits ateliers et aux imprimeries commerciales.","en":"The 1995 HEIDELBERG GTOZ press, equipped with NP system, is a versatile and reliable sheet-fed offset machine. It is ideal for short to medium print runs with high print quality. Equipped with the NP system, it provides better ink distribution and optimized color control. This press is known for its durability and ease of use, suitable for small workshops and commercial print shops.","ar":"آلة الطباعة هايدلبرغ GTOZ لعام 1995، المجهزة بنظام NP، هي آلة طباعة أوفست تغذية ورق متعددة الاستخدامات وموثوقة. مناسبة للطباعة بكميات صغيرة إلى متوسطة بجودة طباعة عالية. مع نظام NP، توفر توزيعًا أفضل للحبر وتحكمًا محسنًا في الألوان. هذه الآلة معروفة بمتانتها وسهولة استخدامها، ومناسبة للورش الصغيرة ومطابع الأعمال التجارية."}',
                    'slug' => 'heidelberg-gtoz-np',
                    'model' => '{"fr": "GTOZ", "ar": "GTOZ", "en": "GTOZ"}',
                    'brand' => '{"ar": "هايدلبرغ", "en": "HEIDELBERG", "fr": "HEIDELBERG"}',
                    'type' => '{"ar": "أوفست تغذية ورق", "en": "Sheet-fed offset", "fr": "Offset feuille"}',
                    'speed' => '{"ar": "حتى 9,000 ورقة في الساعة", "en": "Up to 9,000 sheets per hour", "fr": "Jusqu’à 9 000 feuilles par heure"}',
                    'resolution' => '{"en":null}',
                    'max_print_size' => '{"ar": "36 × 52 سم", "en": "36 x 52 cm", "fr": "36 x 52 cm"}',
                    'color_capability' => 1,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "بدون اتصال رقمي", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "حوالي 5 كيلو وات أثناء التشغيل", "en": "Approx. 5 kW during operation", "fr": "Env. 5 kW en fonctionnement"}',
                    'condition' => '{"ar": "مستخدم", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 11000.0,
                    'warranty' => NULL,
                    'manufacture_year' => '1995',
                    'images' => '["products\\/01JX3M04DKFN06TK1FM6RVGVAN.jpg","products\\/01JX3M04E74YMB5JCY89XBPBQD.jpg"]',
                    'category_id' => 4,
                    'created_at' => '2025-06-07 12:30:00',
                    'updated_at' => '2025-06-06 21:57:50',
                ),
            5 =>
                array(
                    'id' => 7,
                    'name' => '{"fr": "HEIDELBERG", "ar": "هايدلبرغ", "en": "HEIDELBERG"}',
                    'description' => '{"fr":"La presse HEIDELBERG SORM, datant des années 1980 environ, est une machine offset robuste et fiable. En bon état, elle convient pour des tirages variés avec une qualité d\'impression satisfaisante. Elle est particulièrement adaptée aux ateliers souhaitant une machine éprouvée, capable de gérer des travaux d\'impression classiques avec efficacité.","en":"The HEIDELBERG SORM press, from the approximate 1980s, is a robust and reliable offset printing machine. In good condition, it is suitable for various print runs with satisfactory print quality. It is particularly well suited for workshops seeking a proven machine capable of handling classic print jobs efficiently.","ar":"آلة الطباعة هايدلبرغ SORM من أوائل ثمانينيات القرن الماضي تقريبًا، هي آلة طباعة أوفست متينة وموثوقة. بحالة جيدة، تناسب الطباعة بمختلف الكميات وجودة طباعة مرضية. وهي مناسبة بشكل خاص للورش التي تبحث عن آلة مجربة وقادرة على التعامل مع أعمال الطباعة التقليدية بكفاءة."}',
                    'slug' => 'heidelberg-sorm-198x',
                    'model' => '{"fr": "SORM", "ar": "SORM", "en": "SORM"}',
                    'brand' => '{"ar": "هايدلبرغ", "en": "HEIDELBERG", "fr": "HEIDELBERG"}',
                    'type' => '{"ar": "أوفست", "en": "Offset", "fr": "Offset"}',
                    'speed' => '{"ar": "حتى 6000 ورقة في الساعة", "en": "Up to 6,000 sheets per hour", "fr": "Jusqu’à 6 000 feuilles par heure"}',
                    'resolution' => '{"en":null}',
                    'max_print_size' => '{"ar": "غير محدد", "en": "Not specified", "fr": "Non spécifié"}',
                    'color_capability' => 0,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "بدون اتصال رقمي", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "غير محدد", "en": "Not specified", "fr": "Non spécifié"}',
                    'condition' => '{"ar": "بحالة جيدة", "en": "Good condition", "fr": "Bon état"}',
                    'stock_quantity' => 1,
                    'price' => 4000.0,
                    'warranty' => NULL,
                    'manufacture_year' => '1982',
                    'images' => '["products\\/01JX3MZ3TGRH6Z8BWFN3Y6FTM0.jpg"]',
                    'category_id' => 3,
                    'created_at' => '2025-06-07 12:40:00',
                    'updated_at' => '2025-06-06 22:14:45',
                ),
            6 =>
                array(
                    'id' => 8,
                    'name' => '{"fr": "HEIDELBERG", "ar": "هايدلبرغ", "en": "HEIDELBERG"}',
                    'description' => '{"fr":"La presse HEIDELBERG KORD grise de 1999 est une machine offset feuille conçue pour le format 45×64 cm. Cette machine est reconnue pour sa robustesse et sa précision, offrant une excellente qualité d\'impression. Adaptée pour des tirages moyens à élevés, elle est idéale pour des travaux commerciaux variés nécessitant un format plus grand que le standard A3.","en":"The 1999 HEIDELBERG KORD grise press is a sheet-fed offset machine designed for 45×64 cm format. This machine is known for its robustness and precision, providing excellent print quality. Suitable for medium to large print runs, it is ideal for various commercial jobs requiring a larger format than the standard A3.","ar":"آلة الطباعة هايدلبرغ KORD الرمادية لعام 1999 هي آلة طباعة أوفست تغذية ورق مصممة لحجم 45×64 سم. تشتهر هذه الآلة بمتانتها ودقتها، مما يوفر جودة طباعة ممتازة. مناسبة للطباعة بكميات متوسطة إلى كبيرة، وهي مثالية للأعمال التجارية المتنوعة التي تتطلب حجمًا أكبر من A3 القياسي."}',
                    'slug' => 'heidelberg-kord-grise-1999',
                    'model' => '{"fr": "KORD grise", "ar": "KORD الرمادية", "en": "KORD grise"}',
                    'brand' => '{"ar": "هايدلبرغ", "en": "HEIDELBERG", "fr": "HEIDELBERG"}',
                    'type' => '{"ar": "أوفست تغذية ورق", "en": "Sheet-fed offset", "fr": "Offset feuille"}',
                    'speed' => '{"ar": "حتى 10,000 ورقة في الساعة", "en": "Up to 10,000 sheets per hour", "fr": "Jusqu’à 10 000 feuilles par heure"}',
                    'resolution' => '{"en":""}',
                    'max_print_size' => '{"ar": "45 × 64 سم", "en": "45 x 64 cm", "fr": "45 x 64 cm"}',
                    'color_capability' => 1,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "بدون اتصال رقمي", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "حوالي 6 كيلو وات أثناء التشغيل", "en": "Approx. 6 kW during operation", "fr": "Env. 6 kW en fonctionnement"}',
                    'condition' => '{"ar": "مستخدم", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 13000.0,
                    'warranty' => NULL,
                    'manufacture_year' => '1999',
                    'images' => '["products\\/01JX3MXHT02YC5VYCN7DX69QD5.jpg"]',
                    'category_id' => 3,
                    'created_at' => '2025-06-07 12:50:00',
                    'updated_at' => '2025-06-06 22:13:54',
                ),
            7 =>
                array(
                    'id' => 9,
                    'name' => '{"fr": "HEIDELBERG", "ar": "هايدلبرغ", "en": "HEIDELBERG"}',
                    'description' => '{"fr":"La presse HEIDELBERG GTO 52 de 1985 est une machine offset feuille reconnue pour sa robustesse et sa qualité d\'impression. Équipée du système de mouillage Aquaquick, elle permet une meilleure gestion de l\'humidification de la plaque, ce qui améliore la précision des couleurs et la qualité globale de l\'impression. Idéale pour les travaux commerciaux de taille moyenne.","en":"The 1985 HEIDELBERG GTO 52 is a sheet-fed offset press known for its durability and print quality. Equipped with the Aquaquick dampening system, it offers improved control of plate moistening, enhancing color accuracy and overall print quality. Ideal for medium-sized commercial print jobs.","ar":"آلة الطباعة هايدلبرغ GTO 52 لعام 1985 هي آلة أوفست تغذية ورق معروفة بمتانتها وجودة الطباعة. مزودة بنظام الترطيب Aquaquick، الذي يوفر تحكمًا محسّنًا في ترطيب اللوحة، مما يحسّن دقة الألوان وجودة الطباعة بشكل عام. مثالية للأعمال التجارية متوسطة الحجم."}',
                    'slug' => 'heidelberg-gto-52-1985-aquaquick',
                    'model' => '{"fr": "GTO 52", "ar": "GTO 52", "en": "GTO 52"}',
                    'brand' => '{"ar": "هايدلبرغ", "en": "HEIDELBERG", "fr": "HEIDELBERG"}',
                    'type' => '{"ar": "أوفست تغذية ورق", "en": "Sheet-fed offset", "fr": "Offset feuille"}',
                    'speed' => '{"ar": "حتى 9000 ورقة في الساعة", "en": "Up to 9,000 sheets per hour", "fr": "Jusqu’à 9 000 feuilles par heure"}',
                    'resolution' => NULL,
                    'max_print_size' => '{"ar": "36 × 52 سم", "en": "36 x 52 cm", "fr": "36 x 52 cm"}',
                    'color_capability' => 1,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "بدون اتصال رقمي", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "حوالي 5 كيلو وات أثناء التشغيل", "en": "Approx. 5 kW during operation", "fr": "Env. 5 kW en fonctionnement"}',
                    'condition' => '{"ar": "مستخدم", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 7500.0,
                    'warranty' => NULL,
                    'manufacture_year' => '1985',
                    'images' => '["products\\/01JX3MJFSJDZ4YBT85E0T95Q6E.jpg"]',
                    'category_id' => 3,
                    'created_at' => '2025-06-07 13:05:00',
                    'updated_at' => '2025-06-07 13:05:00',
                ),
            8 =>
                array(
                    'id' => 10,
                    'name' => '{"fr": "HEIDELBERG", "ar": "هايدلبرغ", "en": "HEIDELBERG"}',
                    'description' => '{"fr":"La presse HEIDELBERG GTO de 1998 est une machine offset feuille polyvalente, adaptée pour un format d\'impression de 32×46 cm. Elle offre une grande précision et une qualité d\'impression élevée, idéale pour divers travaux commerciaux. Cette machine est robuste et fiable, parfaite pour des tirages de petite à moyenne série.","en":"The 1998 HEIDELBERG GTO is a versatile sheet-fed offset press designed for a 32×46 cm print format. It delivers high precision and print quality, suitable for a variety of commercial print jobs. This machine is robust and reliable, ideal for small to medium print runs.","ar":"آلة الطباعة هايدلبرغ GTO لعام 1998 هي آلة أوفست تغذية ورق متعددة الاستخدامات، مصممة لحجم طباعة 32×46 سم. توفر دقة وجودة طباعة عالية، مناسبة لمجموعة متنوعة من أعمال الطباعة التجارية. هذه الآلة متينة وموثوقة، مثالية للطباعة بكميات صغيرة إلى متوسطة."}',
                    'slug' => 'heidelberg-gto-1998-ft-32x46',
                    'model' => '{"fr": "GTO", "ar": "GTO", "en": "GTO"}',
                    'brand' => '{"ar": "هايدلبرغ", "en": "HEIDELBERG", "fr": "HEIDELBERG"}',
                    'type' => '{"ar": "أوفست تغذية ورق", "en": "Sheet-fed offset", "fr": "Offset feuille"}',
                    'speed' => '{"ar": "حتى 9000 ورقة في الساعة", "en": "Up to 9,000 sheets per hour", "fr": "Jusqu’à 9 000 feuilles par heure"}',
                    'resolution' => '{"en":null}',
                    'max_print_size' => '{"ar": "32 × 46 سم", "en": "32 x 46 cm", "fr": "32 x 46 cm"}',
                    'color_capability' => 1,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "بدون اتصال رقمي", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "حوالي 5 كيلو وات أثناء التشغيل", "en": "Approx. 5 kW during operation", "fr": "Env. 5 kW en fonctionnement"}',
                    'condition' => '{"ar": "مستخدم", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 8000.0,
                    'warranty' => NULL,
                    'manufacture_year' => '1998',
                    'images' => '["products\\/01JX3MVQW54PVJS3NZZ345XE15.jpg","products\\/01JX3MVQWHKZK2FQEWHTCY520R.jpg"]',
                    'category_id' => 3,
                    'created_at' => '2025-06-07 13:20:00',
                    'updated_at' => '2025-06-06 22:12:55',
                ),
            9 =>
                array(
                    'id' => 11,
                    'name' => '{"fr": "HEIDELBERG", "ar": "هايدلبرغ", "en": "HEIDELBERG"}',
                    'description' => '{"fr":"La presse typographique HEIDELBERG GT de 1998 est une presse à platine réputée pour sa fiabilité dans les travaux de dorure, de découpe et d’impression en relief. Elle accepte un format maximum de 34 × 46 cm, ce qui en fait un excellent choix pour les impressions spécialisées, les étiquettes, les emballages et les cartons pliants.","en":"The 1998 HEIDELBERG GT is a platen letterpress machine known for its reliability in hot foil stamping, die-cutting, and relief printing jobs. It supports a maximum format of 34 × 46 cm, making it ideal for specialty printing, labels, packaging, and folding cartons.","ar":"آلة الطباعة HEIDELBERG GT لعام 1998 هي آلة طباعة بلاتينية معروفة بموثوقيتها في أعمال الطباعة البارزة، التذهيب الساخن، والقطع بالقالب. تدعم حجم طباعة أقصى يبلغ 34 × 46 سم، مما يجعلها مثالية للطباعة المتخصصة مثل الملصقات والتغليف والصناديق القابلة للطي."}',
                    'slug' => 'heidelberg-gt-1998-platine',
                    'model' => '{"fr": "GT", "ar": "GT", "en": "GT"}',
                    'brand' => '{"ar": "هايدلبرغ", "en": "HEIDELBERG", "fr": "HEIDELBERG"}',
                    'type' => '{"ar": "آلة طباعة بلاتينية", "en": "Platen letterpress", "fr": "Presse typographique à platine"}',
                    'speed' => '{"ar": "حتى 5000 ورقة في الساعة", "en": "Up to 5,000 sheets per hour", "fr": "Jusqu’à 5 000 feuilles par heure"}',
                    'resolution' => '{"en":null}',
                    'max_print_size' => '{"ar": "34 × 46 سم", "en": "34 x 46 cm", "fr": "34 x 46 cm"}',
                    'color_capability' => 0,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "لا يوجد اتصال رقمي", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "حوالي 3 كيلو وات", "en": "Approx. 3 kW", "fr": "Environ 3 kW"}',
                    'condition' => '{"ar": "مستخدم", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 6200.0,
                    'warranty' => NULL,
                    'manufacture_year' => '1998',
                    'images' => '["products\\/01JX3N7MF84VY5YF3YHK9J2HRY.jpg","products\\/01JX3N7MFH1S6YMC818S7JEDD3.jpg"]',
                    'category_id' => 2,
                    'created_at' => '2025-06-07 13:25:00',
                    'updated_at' => '2025-06-06 22:19:25',
                ),
            10 =>
                array(
                    'id' => 12,
                    'name' => '{"fr": "OFEM", "ar": "أوفيم", "en": "OFEM"}',
                    'description' => '{"fr":"La OFEM Juliette 758 de 2003 est une plieuse-colleuse conçue pour les travaux d\'emballage et de finition. Elle offre une performance fiable pour le pliage et le collage de boîtes pliantes, idéale pour les moyennes séries. Sa conception robuste garantit une longue durée de vie et une grande précision de traitement.","en":"The 2003 OFEM Juliette 758 is a folder-gluer machine designed for packaging and finishing jobs. It delivers reliable performance for folding and gluing folding cartons, ideal for medium production runs. Its sturdy construction ensures long service life and high processing precision.","ar":"آلة OFEM Juliette 758 لعام 2003 هي آلة طي ولصق مصممة لأعمال التعبئة والتغليف والتشطيب. توفر أداءً موثوقًا لطي ولصق علب الكرتون، وهي مثالية للإنتاج المتوسط. تصميمها المتين يضمن عمر خدمة طويل ودقة عالية في المعالجة."}',
                    'slug' => 'ofem-juliette-758-2003',
                    'model' => '{"fr": "Juliette 758", "ar": "جولييت 758", "en": "Juliette 758"}',
                    'brand' => '{"ar": "أوفيم", "en": "OFEM", "fr": "OFEM"}',
                    'type' => '{"ar": "آلة طي ولصق", "en": "Folder-gluer", "fr": "Plieuse-colleuse"}',
                    'speed' => '{"ar": "تصل إلى 300 متر في الدقيقة", "en": "Up to 300 meters per minute", "fr": "Jusqu’à 300 mètres par minute"}',
                    'resolution' => '{"en":null}',
                    'max_print_size' => '{"ar": "يعتمد على تخطيط العلبة", "en": "Depends on carton layout", "fr": "Dépend de la mise en page de la boîte"}',
                    'color_capability' => 0,
                    'duplex' => 0,
                    'connectivity' => '{"ar": "غير متصلة رقميًا", "en": "No digital connectivity", "fr": "Pas de connectivité numérique"}',
                    'power_consumption' => '{"ar": "تقريبًا 5 كيلو وات", "en": "Approx. 5 kW", "fr": "Env. 5 kW"}',
                    'condition' => '{"ar": "مستخدمة", "en": "Used", "fr": "Utilisée"}',
                    'stock_quantity' => 1,
                    'price' => 9800.0,
                    'warranty' => NULL,
                    'manufacture_year' => '2003',
                    'images' => '["products\\/01JX3PJBHYTNTCNZAN5PYT75B3.jpg","products\\/01JX3PJBJBEVN5WXQHRX1WDC6K.jpg"]',
                    'category_id' => 6,
                    'created_at' => '2025-06-07 13:20:00',
                    'updated_at' => '2025-06-06 22:42:44',
                ),
        ));


    }
}
